name: Node.js Package
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2          
      - name: Prepare Packages
        run: |
          pnpm i
          pnpm build
          cp README.md packages/cli/README.md
          cp logo.png packages/cli/
      - name: Publish @dotenv-run/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd packages/cli && npm publish --access public
